### ISSUE TITLE
'VisionTransformer' object has no attribute 'no_embed_class'

### ISSUE THREAD

**Issue by oomensusan** [faresmalik/SEViT#1]
Hi Team,

 I am trying to run the test.py file, but during running I am getting the below error , can u help with the issue please?
![image](https://user-images.githubusercontent.com/8180920/211542557-66e6bf30-3f0d-4c51-8d53-69e8a3f52232.png)

**Comment by faresmalik** [comment]
> Hi Team,
> 
> I am trying to run the test.py file, but during running I am getting the below error , can u help with the issue please? ![image](https://user-images.githubusercontent.com/8180920/211542557-66e6bf30-3f0d-4c51-8d53-69e8a3f52232.png)

Hello! 

Please make sure that you have installed version 0.4.12 for timm library. This should work fine!

**Comment by oomensusan** [comment]
Thank you, able to run now . Issue has been resolved
