### ISSUE TITLE
The accuracy of mlp classifier I trained is lower than you

### ISSUE THREAD

**Issue by huozitong** [faresmalik/SEViT#4]
Hi, team, can you provide concrete trainning procedures and the structure of the mlp classifier.
I used your mlp classifier network, and followed your insturction step by step, however, the accuracy of mlp classifier I trained can only reach 90%

**Comment by faresmalik** [comment]
Hello! 

Thanks for raising this issue. Have you been able to check the MLP's weights? We have already uploaded them. 

If you still need to train the MLPs by yourself: 

1. For the Fundoscopy dataset, ALL MLPs should not exceed 90% (Please check Fig 3 (a) in the paper). 

2. For the Chest X-ray dataset, All MLPs should be within the range of (88% - 94%) (Please check Fig 3 (a) in the paper). 

In the case of training the MLPs from scratch, I suggest running some experiments with different seeds.

**Comment by huozitong** [comment]
Thank you for your answer. I noticed the MLP's weights you provided. The accuracy of MLP I trained is only 90% but the one you provide is 94%. I don't know how to train the MLP to reach the accuracy you provide.
This is my block_0 MLP training result.

![E35Y~)$TY10$Q)F4AH %94T](https://github.com/faresmalik/SEViT/assets/55731580/b1f893a7-dcf6-4c16-977e-952f51e6d8b5)

**Comment by faresmalik** [comment]
Well. I suggest the following: 

1. Ensure that the data transformations used are similar to the ones provided in this repo. 
2. Run experiments with different seeds. 
3. Use a scheduler while training the MLPs (scheduler = StepLR(optimizer=optimizer, step_size=15, gamma=0.1))
4. Make sure you pass the features only without the cls token. Each block will output 197x768 You should skip the first token and take the rest (196 x 768)

You need to run it with different seeds and keep track of the results.

**Comment by huozitong** [comment]
Thank you for your suggestions. However, the results of my model are still not good. 
Whether you used Dropout Layer in your model or not?
![3 1U51A{V$)W6`6MEK57)Z6](https://github.com/faresmalik/SEViT/assets/55731580/9f4f541c-1465-4ffd-b8a4-3bd10c85216e)

**Comment by faresmalik** [comment]
In our experiments, we tried both. However, we found that eliminating the dropout gave better results. 

In the code you shared, the dropout is there, but it's not used in the forward pass. Technically, this means that we didn't use the dropout. Have you tried the suggested solutions?

**Comment by huozitong** [comment]
Thank you for your suggestions. I retrained the MLP following the advice you provided and got expected results.

**Comment by faresmalik** [comment]
Fantastic! 

Glad to hear that it has been resolved. Please star the repo if you found it useful! 

I will close this issue.
